services:
  sonarqube:
    image: brainiac/sonarqube
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarnet

  db:
    image: postgres:17.5
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d
    networks:
      - sonarnet

  runner1:
    image: brainiac/local-github-runner
    container_name: github-runner-${GITHUB_REPO_1}
    environment:
      REPO_URL: https://github.com/${GITHUB_OWNER}/${GITHUB_REPO_1}
      RUNNER_NAME: runner-${GITHUB_REPO_1}
      RUNNER_WORKDIR: /_work/runner-${GITHUB_REPO_1}
      GITHUB_OWNER: ${GITHUB_OWNER}
      GITHUB_REPO: ${GITHUB_REPO_1}
      LABELS: runner-${GITHUB_REPO_1}
      ACCESS_TOKEN: ${GH_RUNNER_TOKEN}
      SONAR_TOKEN: ${SONAR_TOKEN}
      PROJECT_KEY: ${GITHUB_REPO_1}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
      CONNECTION_NAME: ${CONNECTION_NAME}
      SNOW_CONFIG_B64: ${SNOW_CONFIG_B64:-default_value_here}
      SNOW_KEY_B64: ${SNOW_KEY_B64:-default_value_here}
      DISABLE_AUTOMATIC_DEREGISTRATION: "true"
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /actions-runner-config/${GITHUB_REPO_1}
      UNSET_CONFIG_VARS: "true"
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_config:/actions-runner-config/${GITHUB_REPO_1}
      - sql_unit_report:/home/docker/sql-report-vol
      - ./sql-unit-reports:/home/docker/sql-unit-reports
    networks:
      - sonarnet

  nginx-server:
    image: nginx
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - sql_unit_report:/usr/share/nginx/html:ro
    networks:
      - sonarnet

volumes:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  runner_config:
  sql_unit_report:
    name: sql_unit_report

networks:
  sonarnet:
