name: Docker Build and Push to Docker Hub (Multi-Arch)

on:
  push:
    branches:
      - main
    paths:
      - 'github-runner/**'
      - 'sonarqube/**'
      - '.github/workflows/docker-publish.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push GitHub runner image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./github-runner
          file: ./github-runner/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            brainiac/local-github-runner:latest

      - name: Build and push SonarQube image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./sonarqube
          file: ./sonarqube/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            brainiac/sonarqube:latest
